version: "3.8"

services:
    postgres:
      image: postgres:latest
      restart: always
      environment: 
        POSTGRES_USER: ${SPRING_DATASOURC_USERNAME}
        POSTGRES_PASSWORD: ${SPRING_DATASOURC_PASSWORD}
        POSTGRES_DB: ${SPRING_DATASOURC_DB}

        ports:
          - "5432:5432"

        volumenes:
          - ./postgres:/var/lib/postgresql/data
